@startuml

package com.japhy.design.builder {

    class Person {
        - name: String
        - age: int
        - address: String

        + Person(builder: Builder)
        + Person(name: String, age:int, address: String)
        + String getName()
        + int getAge()
        + String getAddress()
        + builder() {static}: Builder
        + toString(): String
    }
    class Builder {
        - name: String
        - age: int
        - address: String
        + name(name: String): Builder
        + age(age: int): Builder
        + address(address: String) Builder
        + build() Person
    }

    Person ..> Builder
}

@enduml