
server:
  port: 9001

logging.level.org.springframework.boot.autoconfigure.security: INFO
spring:
  security:
    user:
      name: japhy
      password: japhy
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug
custom.test: 1

---
spring:
  config:
    activate:
      on-profile: basic




