
server:
  port: 9001

logging.level.org.springframework.boot.autoconfigure.security: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_base?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql
  thymeleaf:
    cache: false
  security:
    user:
      name: japhy
      password: japhy
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: debug
custom.test: 1

---
spring:
  profiles: basic




