japhy.age: ${random.long(10)}
japhy.phone: ddd
japhy.enabled: true
yaml-property: yaml-property
spring:
  profiles:
    active: dev

logging:
  level:
    root: trace
---
japhy.name: japhy
japhy.age: ${random.long(10)}
japhy.enabled: true
japhy.phone: ddd
japhy.mavenProject: @maven.project@
japhy.yamlProperty: ${yaml-property}
spring:
  config:
    activate:
      on-profile: dev
---
japhy.age: ${random.long(20)}
japhy.phone: test
japhy.enabled: true
spring:
  cloud:
    refresh:
      extra-refreshable:
  config:
    activate:
      on-profile: test

