
swagger:
  enabled: false

spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource: # use in-memory db for unit testing, 默认不配置使用 username: sa and password为空的默认库
    url: jdbc:h2:mem:jpa_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      connection-test-query: "SELECT 1"
    #    schema: classpath:/db/schema.sql
    h2:
      console:
        enabled: true
  security:
    user:
      password: user
      name: user
    oauth2:
      client:
        provider:
          jwt
  sql:
    init:
      platform: h2
      continue-on-error: false
logging:
#  file:
#    name: web-base.log
#    path: /logs/
  level:
    root: info

