
swagger:
  enabled: false

spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/web_base?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql
  security:
    user:
      password: user
    oauth2:
      client:
        provider:
          jwt
logging:
#  file:
#    name: web-base.log
#    path: /logs/
  level:
    root: info

