server:
  port: 9999
  application:
    name: web-base
  devtools:
    remote:
      secret: secret
  jackson:
    time-zone: Asia/Shanghai

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      base-path: /mgm
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

custom:
  word: hello
spring:
  mvc:
    problemdetails:
      enabled: true
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
springdoc:
  version: '@project.version@'
  swagger-ui:
    use-root-path: true


