server:
  port: 9999

spring:
  application:
    name: web-base
  devtools:
    remote:
      secret: secret
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      base-path: /mgm
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


custom:
  word: hello

