japhy.age: ${random.long(10)}
japhy.phone: "ddd"
japhy.enabled: true
yaml-property: "yaml-property"
spring:
  profiles:
    active: dev
---
spring.profiles: dev
japhy.name: japhy
japhy.age: ${random.long(10)}
japhy.enabled: true
japhy.phone: "ddd"
japhy.mavenProject: '@maven.project@'
japhy.yamlProperty: ${yaml-property}
---
spring.profiles: test
japhy.age: ${random.long(20)}
japhy.phone: "test"
japhy.enabled: true
spring:
  cloud:
    refresh:
      extra-refreshable:
