spring:
  kafka:
    bootstrap-servers: 39.99.149.197:9092
    consumer:
      group-id: japhyDemo
    listener:
      missingTopicsFatal: false
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
