
spring:
  kafka:
#    bootstrap-servers:
#      - 39.99.155.113:9092
    consumer:
      group-id: japhyDemo
      auto-offset-reset: earliest
    listener:
      missingTopicsFatal: false
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
debug: true
