hbase:
  rootDir: ./hbase
  zookeeper:
    quorum: xuehai-nn,xuehai-dn,xuehai-cm
    property:
      clientPort: 2181

zookeeper:
  znode:
    parent: /hbase

logging:
  level: debug
  level.web: debug
